# ASSIGNMENT 1 
Basic Python
Name: Ashwath Jude J
Roll no:311119106005

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
x= s.split()
print(x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
txt1="The diameter of {planet} is {diameter} kilometers".format(planet = "Earth",diameter=12742)
print(txt1)

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [9]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
array=np.arange(20,35,2)
print(array) 

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a, b), axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [19]:
data = [10,20,30]
df = pd.DataFrame(data, columns=['Numbers'])
print(df)

   Numbers
0       10
1       20
2       30


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [25]:
from dateutil.parser import parse
date_series = pd.Series(['Jan 2023', 'Feb 2023'])
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

0   2023-01-11
1   2023-02-11
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [22]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
df = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age']) 
print(df)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
